services:
  moontv-core-fnos:
    image: ghcr.nju.edu.cn/moontechlab/lunatv:latest
    container_name: moontv-core-fnos
    restart: always
    ports:
      - '22388:22388'
    environment:
      - USERNAME=${wizard_username:-admin}
      - PASSWORD=${wizard_password:-admin_password}
      - NEXT_PUBLIC_STORAGE_TYPE=kvrocks
      - KVROCKS_URL=redis://moontv-kvrocks-fnos:6666
      - PORT=22388
    networks:
      - moontv-network
    depends_on:
      moontv-kvrocks-fnos:
        condition: service_started
  moontv-kvrocks-fnos:
    image: apache/kvrocks
    container_name: moontv-kvrocks-fnos
    restart: always
    volumes:
      - kvrocks-data-fnos:/var/lib/kvrocks
    networks:
      - moontv-network

networks:
  moontv-network:
    driver: bridge

volumes:
  kvrocks-data-fnos:
